package typosquat

import (
	"bufio"
	"bytes"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"sync"
	"time"

	"github.com/vahapogut/trustdiff/internal/model"
)

// RefreshTTL is how long a refreshed copy is preferred over the embedded
// snapshot. The sources update monthly at most, so a month is fresh enough.
const RefreshTTL = 30 * 24 * time.Hour

// listsSubdir is the directory under the trustdiff cache directory that holds the
// refreshed lists. It is a subdirectory, not a set of loose files, so that the
// httpcache entries and the lists cannot be mistaken for each other.
const listsSubdir = "lists"

// noticePrefix opens the first line of every list file.
const noticePrefix = "# NOTICE "

// dateLayout is the date format of the NOTICE line.
const dateLayout = "2006-01-02"

// listed are the ecosystems that have a popular list.
var listed = []model.Ecosystem{model.NPM, model.PyPI, model.Cargo}

//go:embed data/npm.txt data/pypi.txt data/cargo.txt
var embedded embed.FS

// List is the popular names of one ecosystem together with the provenance the
// NOTICE line of its file records.
type List struct {
	Ecosystem model.Ecosystem
	// Source is the URL (or URLs, space separated) the names came from.
	Source string
	// Fetched is the day the names were downloaded, at UTC midnight.
	Fetched time.Time
	// License is the license of the source data as observed on that day.
	License string
	// Names are the canonical names, sorted and unique.
	Names []string
}

// Set builds the lookup structure for the names.
func (l *List) Set() *Set { return NewSet(l.Ecosystem, l.Names) }

// Lists holds one popular list per ecosystem and where each came from.
type Lists struct {
	byEco map[model.Ecosystem]*List
	sets  map[model.Ecosystem]*Set
	// origin says, per ecosystem, whether the list is "embedded" or the path of
	// the refreshed file it was read from.
	origin map[model.Ecosystem]string
}

// Popular returns the popular set of an ecosystem. ok is false, and the Set nil,
// for ecosystems without a list (Deno and JSR in this milestone).
func (l *Lists) Popular(eco model.Ecosystem) (*Set, bool) {
	s, ok := l.sets[eco]
	return s, ok
}

// List returns the list of an ecosystem with its provenance.
func (l *Lists) List(eco model.Ecosystem) (*List, bool) {
	list, ok := l.byEco[eco]
	return list, ok
}

// Origin reports where the list of an ecosystem came from: "embedded" or the
// path of the refreshed file. Empty for ecosystems without a list.
func (l *Lists) Origin(eco model.Ecosystem) string { return l.origin[eco] }

func newLists() *Lists {
	return &Lists{
		byEco:  map[model.Ecosystem]*List{},
		sets:   map[model.Ecosystem]*Set{},
		origin: map[model.Ecosystem]string{},
	}
}

// NewLists assembles lists supplied by the caller, for tests and for callers
// with a source of their own. Their origin is reported as "custom".
func NewLists(lists ...*List) *Lists {
	out := newLists()
	for _, list := range lists {
		if list != nil {
			out.add(list, "custom")
		}
	}
	return out
}

func (l *Lists) add(list *List, origin string) {
	l.byEco[list.Ecosystem] = list
	l.sets[list.Ecosystem] = list.Set()
	l.origin[list.Ecosystem] = origin
}

var (
	embeddedOnce  sync.Once
	embeddedLists *Lists
)

// Embedded returns the snapshot compiled into the binary. The files are
// generated by scripts/gen-toplists and checked by the tests, so a file that does
// not parse is a build defect and panics, like a malformed compiled-in regexp.
func Embedded() *Lists {
	embeddedOnce.Do(func() {
		lists := newLists()
		for _, eco := range listed {
			data, err := fs.ReadFile(embedded, dataFile(eco))
			if err != nil {
				panic(fmt.Sprintf("typosquat: embedded list for %s: %v", eco, err))
			}
			list, err := ParseList(eco, data)
			if err != nil {
				panic(fmt.Sprintf("typosquat: embedded list for %s: %v", eco, err))
			}
			lists.add(list, "embedded")
		}
		embeddedLists = lists
	})
	return embeddedLists
}

// dataFile is the relative name of an ecosystem's list file, in the embedded
// data directory and in the refreshed lists directory alike.
func dataFile(eco model.Ecosystem) string {
	return "data/" + string(eco) + ".txt"
}

// ListsDir is the directory under the trustdiff cache directory cacheDir where
// Refresh writes and Load reads the refreshed lists.
func ListsDir(cacheDir string) string {
	return filepath.Join(cacheDir, listsSubdir)
}

// Load returns the popular lists, preferring for each ecosystem the refreshed
// copy under ListsDir(cacheDir) when it exists, parses and was fetched less than
// RefreshTTL before now, and falling back to the embedded snapshot otherwise. A
// refreshed copy that is stale or unreadable is reported through log, never as an
// error: the embedded snapshot is always available. A nil log discards.
func Load(cacheDir string, now time.Time, log *slog.Logger) *Lists {
	if log == nil {
		log = slog.New(slog.DiscardHandler)
	}
	lists := newLists()
	base := Embedded()
	for _, eco := range listed {
		path := filepath.Join(ListsDir(cacheDir), string(eco)+".txt")
		list, err := readList(eco, path)
		switch {
		case err == nil && now.Sub(list.Fetched) <= RefreshTTL:
			lists.add(list, path)
			continue
		case err == nil:
			log.Info("refreshed popular list is stale, using the embedded snapshot", "ecosystem", eco, "path", path, "fetched", list.Fetched.Format(dateLayout))
		case errors.Is(err, fs.ErrNotExist):
			log.Debug("no refreshed popular list, using the embedded snapshot", "ecosystem", eco, "path", path)
		default:
			log.Warn("refreshed popular list unreadable, using the embedded snapshot", "ecosystem", eco, "path", path, "error", err)
		}
		embeddedList, _ := base.List(eco)
		lists.add(embeddedList, "embedded")
	}
	return lists
}

// readList reads and parses one list file.
func readList(eco model.Ecosystem, path string) (*List, error) {
	data, err := os.ReadFile(path) // #nosec G304 -- the path is the lists directory the caller chose plus a fixed ecosystem file name
	if err != nil {
		return nil, err
	}
	return ParseList(eco, data)
}

// ParseList decodes a list file: the NOTICE line, then one name per line. Lines
// that start with # are comments and blank lines are ignored. Names are
// canonicalized, sorted and deduplicated, so a hand-edited file still loads.
func ParseList(eco model.Ecosystem, data []byte) (*List, error) {
	scanner := bufio.NewScanner(bytes.NewReader(data))
	if !scanner.Scan() {
		return nil, errors.New("empty file")
	}
	list, err := parseNotice(scanner.Text())
	if err != nil {
		return nil, err
	}
	list.Ecosystem = eco
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if c := Canonical(eco, line); c != "" {
			list.Names = append(list.Names, c)
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("reading names: %w", err)
	}
	slices.Sort(list.Names)
	list.Names = slices.Compact(list.Names)
	if len(list.Names) == 0 {
		return nil, errors.New("no names after the NOTICE line")
	}
	return list, nil
}

// parseNotice decodes the first line, which reads
//
//	# NOTICE source: <url>; fetched: <yyyy-mm-dd>; license: <text>
//
// The license runs to the end of the line and may itself contain "; ".
func parseNotice(line string) (*List, error) {
	rest, ok := strings.CutPrefix(strings.TrimSpace(line), noticePrefix)
	if !ok {
		return nil, fmt.Errorf("first line must start with %q, got %q", strings.TrimSpace(noticePrefix), line)
	}
	fields := strings.SplitN(rest, "; ", 3)
	if len(fields) != 3 {
		return nil, fmt.Errorf("NOTICE line must carry source, fetched and license, got %q", line)
	}
	list := &List{}
	for i, key := range []string{"source", "fetched", "license"} {
		value, ok := strings.CutPrefix(strings.TrimSpace(fields[i]), key+":")
		if !ok {
			return nil, fmt.Errorf("NOTICE line: field %d must start with %q, got %q", i+1, key+":", fields[i])
		}
		if value = strings.TrimSpace(value); value == "" {
			return nil, fmt.Errorf("NOTICE line: %s is empty", key)
		}
		switch key {
		case "source":
			list.Source = value
		case "fetched":
			fetched, err := time.Parse(dateLayout, value)
			if err != nil {
				return nil, fmt.Errorf("NOTICE line: fetched: %w", err)
			}
			list.Fetched = fetched
		case "license":
			list.License = value
		}
	}
	return list, nil
}

// Notice renders the NOTICE line of the list.
func (l *List) Notice() string {
	return fmt.Sprintf("%ssource: %s; fetched: %s; license: %s", noticePrefix, l.Source, l.Fetched.UTC().Format(dateLayout), l.License)
}

// Encode renders the list file: the NOTICE line and the sorted names.
func (l *List) Encode() []byte {
	names := slices.Clone(l.Names)
	slices.Sort(names)
	names = slices.Compact(names)
	var b bytes.Buffer
	b.Grow(len(names) * 16)
	b.WriteString(l.Notice())
	b.WriteByte('\n')
	for _, name := range names {
		b.WriteString(name)
		b.WriteByte('\n')
	}
	return b.Bytes()
}

// WriteLists writes one file per list into dir, creating it when needed, as
// <dir>/<ecosystem>.txt. Each file is written to a temporary name and renamed
// into place, so a reader never sees a partial list.
func WriteLists(dir string, lists []*List) error {
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return fmt.Errorf("creating %s: %w", dir, err)
	}
	for _, list := range lists {
		name := string(list.Ecosystem) + ".txt"
		tmp, err := os.CreateTemp(dir, name+".*.tmp")
		if err != nil {
			return fmt.Errorf("creating temporary file in %s: %w", dir, err)
		}
		tmpName := tmp.Name()
		if _, err := tmp.Write(list.Encode()); err != nil {
			_ = tmp.Close()
			_ = os.Remove(tmpName)
			return fmt.Errorf("writing %s: %w", tmpName, err)
		}
		if err := tmp.Close(); err != nil {
			_ = os.Remove(tmpName)
			return fmt.Errorf("closing %s: %w", tmpName, err)
		}
		if err := os.Rename(tmpName, filepath.Join(dir, name)); err != nil {
			_ = os.Remove(tmpName)
			return fmt.Errorf("renaming %s: %w", tmpName, err)
		}
	}
	return nil
}
