// Package typosquat decides whether a package name looks like a misspelling of a
// popular package in the same ecosystem. It is the engine behind check TD008
// (typosquat-suspect) and knows nothing about registries: it compares names
// against a Set of popular names with a fixed list of rules (edit distance with a
// length-based threshold, adjacent transpositions, separator swaps, npm scope
// confusion, language affixes such as py or node, digit and letter confusables,
// and common-word insertions such as -utils) and reports the closest neighbor
// together with the rule that matched.
//
// The popular names come from snapshots embedded in the binary (data/*.txt, one
// file per ecosystem, generated by scripts/gen-toplists) or from a refreshed copy
// that Refresh writes under the trustdiff cache directory. Load prefers the
// refreshed copy while it is younger than RefreshTTL and falls back to the
// embedded snapshot otherwise, per ecosystem.
//
// Every name is compared in its canonical spelling: model.NormalizeName followed
// by lowercasing, so that "Requests", "requests" and "REQUESTS" are one name on
// PyPI and the crates.io names, which the registry treats case-insensitively, are
// too. A name that is itself popular is never a suspect.
package typosquat

import (
	"strings"

	"github.com/vahapogut/trustdiff/internal/model"
)

// Rule names the heuristic that matched a candidate to a popular neighbor. The
// values are part of the stable evidence of TD008 and never change meaning.
type Rule string

// Rules in the order they are tried. When two neighbors are equally close, the
// earlier rule wins.
const (
	// RuleSeparator matches names that differ only in separators: "-", "_", "."
	// or none, for example python-dateutil and pythondateutil.
	RuleSeparator Rule = "separator-swap"
	// RuleScope matches an npm scope written as a prefix, for example types-foo
	// for @types/foo, or the reverse.
	RuleScope Rule = "scope-confusion"
	// RuleAffix matches a py, python, js or node prefix or suffix added to or
	// removed from a popular name, for example python-requests for requests.
	RuleAffix Rule = "language-affix"
	// RuleConfusable matches names that differ only in the digit and letter pairs
	// l and 1, o and 0, for example 1odash for lodash or pi11ow for pillow. Letter
	// pairs such as i and l are left to a future homoglyph rule.
	RuleConfusable Rule = "confusable-characters"
	// RuleCommonWord matches a popular name with one of the words dev, utils, cli,
	// js or py inserted as a separate token, for example lodash-utils for lodash.
	RuleCommonWord Rule = "common-word"
	// RuleTransposition matches names that differ by one swap of adjacent
	// characters, for example reqeusts for requests.
	RuleTransposition Rule = "transposition"
	// RuleEditDistance matches names within Threshold edits (Damerau-Levenshtein)
	// of a popular name, for example requets for requests.
	RuleEditDistance Rule = "edit-distance"
)

// Rules lists every rule in the order Suspect tries them.
func Rules() []Rule {
	return []Rule{RuleSeparator, RuleScope, RuleAffix, RuleConfusable, RuleCommonWord, RuleTransposition, RuleEditDistance}
}

// separators are the characters ecosystems use between words of a name.
const separators = "-_."

// languageAffixes are tried longest first so that "python" is not read as "py"
// followed by "thon".
var languageAffixes = []string{"python", "node", "py", "js"}

// commonWords are the tokens a squatter appends to a popular name.
var commonWords = map[string]bool{"dev": true, "utils": true, "cli": true, "js": true, "py": true}

// Canonical returns the spelling names are compared in: model.NormalizeName, then
// lowercase, with surrounding whitespace removed.
func Canonical(eco model.Ecosystem, name string) string {
	return strings.ToLower(strings.TrimSpace(model.NormalizeName(eco, name)))
}

// stripSeparators removes every separator so that spellings that differ only in
// them compare equal.
func stripSeparators(s string) string {
	if !strings.ContainsAny(s, separators) {
		return s
	}
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if !strings.ContainsRune(separators, r) {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// scoped reports whether an npm name carries a scope (@scope/name).
func scoped(s string) bool {
	return strings.HasPrefix(s, "@") && strings.Contains(s, "/")
}

// flattenScope writes @scope/name as scope-name, the spelling a squatter uses
// when the scope is not theirs. Unscoped names are returned unchanged.
func flattenScope(s string) string {
	if !scoped(s) {
		return s
	}
	scope, name, _ := strings.Cut(s[1:], "/")
	return scope + "-" + name
}

// foldConfusables maps the confusable digits onto the letters they imitate: 1
// becomes l, 0 becomes o.
func foldConfusables(s string) string {
	if !strings.ContainsAny(s, "10") {
		return s
	}
	return strings.Map(func(r rune) rune {
		switch r {
		case '1':
			return 'l'
		case '0':
			return 'o'
		}
		return r
	}, s)
}

// tokens splits a name at its separators, dropping empty pieces.
func tokens(s string) []string {
	return strings.FieldsFunc(s, func(r rune) bool { return strings.ContainsRune(separators, r) })
}
