// Command gen-confusables derives the ASCII package-name subset of Unicode's
// confusables data. The checksum pins the upstream bytes even though Unicode's
// latest URL moves. Pass -in for a fully offline regeneration.
package main

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"slices"
	"strconv"
	"strings"
	"time"
)

const (
	sourceURL     = "https://www.unicode.org/Public/security/latest/confusables.txt"
	sourceSHA     = "6ed3ee967c9dfdf6677d563c9985182fbc50a2efb7d6059cd57b2e2ce18f5b92"
	sourceVersion = "18.0.0"
)

func main() {
	in := flag.String("in", "", "local upstream confusables.txt; otherwise download the pinned bytes")
	out := flag.String("out", "internal/typosquat/homoglyph_data.go", "generated Go file")
	flag.Parse()
	if err := run(*in, *out); err != nil {
		fmt.Fprintln(os.Stderr, "gen-confusables:", err)
		os.Exit(1)
	}
}

func run(in, out string) error {
	data, err := readSource(in)
	if err != nil {
		return err
	}
	if got := fmt.Sprintf("%x", sha256.Sum256(data)); got != sourceSHA {
		return fmt.Errorf("upstream SHA256 is %s, want %s; review the new Unicode release before updating the pin", got, sourceSHA)
	}
	mapping, err := parse(data)
	if err != nil {
		return err
	}
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by go run ./scripts/gen-confusables; DO NOT EDIT.")
	fmt.Fprintf(&b, "// Source: %s\n// Unicode %s; upstream date 2026-08-06; fetched 2026-09-29.\n// SHA256: %s\n", sourceURL, sourceVersion, sourceSHA)
	fmt.Fprintln(&b, "// Copyright (c) 2026 Unicode, Inc. Unicode License V3; see LICENSE-Unicode.\npackage typosquat")
	fmt.Fprintf(&b, "\n// HomoglyphUnicodeVersion identifies the data behind the bounded skeleton rule.\nconst HomoglyphUnicodeVersion = %q\n", sourceVersion)
	fmt.Fprintln(&b, "\nfunc homoglyphMapping(r rune) string {\nswitch r {")
	keys := make([]rune, 0, len(mapping))
	for r := range mapping {
		keys = append(keys, r)
	}
	slices.Sort(keys)
	for _, r := range keys {
		fmt.Fprintf(&b, "case 0x%04X: return %q\n", r, mapping[r])
	}
	fmt.Fprintln(&b, "default: return \"\"\n}\n}")
	generated, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}
	if err := os.WriteFile(out, generated, 0o644); err != nil {
		return err
	} // #nosec G306 -- generated public source
	fmt.Printf("%s: %d mappings, Unicode %s\n", out, len(mapping), sourceVersion)
	return nil
}

func readSource(in string) ([]byte, error) {
	if in != "" {
		return os.ReadFile(in)
	} // #nosec G304 -- explicit generator input
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, sourceURL, nil)
	if err != nil {
		return nil, err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unicode download: HTTP %d", resp.StatusCode)
	}
	return io.ReadAll(io.LimitReader(resp.Body, 2<<20))
}

// parse keeps only one-rune sources whose entire target is an ASCII package-name
// sequence. Targets are lowercased for Canonical and closed under ASCII mappings
// (notably m -> rn), so applying the resulting skeleton twice changes nothing.
func parse(data []byte) (map[rune]string, error) {
	mapping := map[rune]string{}
	s := bufio.NewScanner(bytes.NewReader(data))
	for line := 1; s.Scan(); line++ {
		text, _, _ := strings.Cut(s.Text(), "#")
		if strings.TrimSpace(text) == "" {
			continue
		}
		parts := strings.Split(text, ";")
		if len(parts) != 3 || strings.TrimSpace(parts[2]) != "MA" {
			return nil, fmt.Errorf("line %d: unsupported record", line)
		}
		src, err := strconv.ParseUint(strings.TrimSpace(parts[0]), 16, 32)
		if err != nil || src > 0x10ffff || src >= 0xd800 && src <= 0xdfff {
			return nil, fmt.Errorf("line %d: invalid source", line)
		}
		var target strings.Builder
		keep := true
		for _, field := range strings.Fields(parts[1]) {
			cp, err := strconv.ParseUint(field, 16, 32)
			if err != nil || cp > 0x10ffff || cp >= 0xd800 && cp <= 0xdfff {
				return nil, fmt.Errorf("line %d: invalid target", line)
			}
			if cp > 127 || !strings.ContainsRune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._-", rune(cp)) {
				keep = false
			}
			target.WriteRune(rune(cp))
		}
		if keep && target.Len() > 0 {
			mapping[rune(src)] = strings.ToLower(target.String())
		}
	}
	if err := s.Err(); err != nil {
		return nil, err
	}
	closed := make(map[rune]string, len(mapping))
	for src, target := range mapping {
		seen := map[string]bool{}
		for step := 0; ; step++ {
			if step >= 64 || len(target) > 4096 {
				return nil, fmt.Errorf("unbounded target for U+%04X", src)
			}
			if seen[target] {
				return nil, fmt.Errorf("cyclic target for U+%04X", src)
			}
			seen[target] = true
			var next strings.Builder
			for _, r := range target {
				if replacement := mapping[r]; replacement != "" {
					next.WriteString(replacement)
				} else {
					next.WriteRune(r)
				}
			}
			if next.String() == target {
				break
			}
			target = next.String()
		}
		closed[src] = target
	}
	return closed, nil
}
