package cli

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The acceptance fixture: one repository with seven package managers, each holding
// a setting that is missing, present and wrong, or already right. It is written
// here rather than kept as files so that the wrong values and the reason each one
// is wrong sit next to the assertions about them.
//
// Every run below passes --offline, which keeps detection from asking a package
// manager on the machine for its version. A test that ran whatever npm happens to
// be installed would pass or fail depending on the developer's laptop.
var doctorFixture = map[string]string{
	// npm 12 through the packageManager field, with an .npmrc that says nothing
	// about the wait.
	"package.json": `{
  "name": "acceptance",
  "packageManager": "npm@12.0.2",
  "workspaces": ["apps/*"]
}
`,
	".npmrc":            "; the project's registry settings\nregistry=https://registry.npmjs.org/\n",
	"package-lock.json": `{"name":"acceptance","lockfileVersion":3,"packages":{}}` + "\n",

	// pnpm 11 in a workspace of its own, with the wait set to an hour: present,
	// believed in, and worth almost nothing.
	"apps/web/package.json": `{
  "name": "web",
  "packageManager": "pnpm@11.2.0"
}
`,
	"apps/web/pnpm-workspace.yaml": `packages:
  - "packages/*"

# Hold new releases back for a while.
minimumReleaseAge: 60
`,
	"apps/web/pnpm-lock.yaml": "lockfileVersion: '9.0'\n",

	// Yarn 4.15, whose gate is a number of minutes and is not set at all.
	"apps/admin/package.json": `{
  "name": "admin",
  "packageManager": "yarn@4.15.0"
}
`,
	"apps/admin/.yarnrc.yml": "nodeLinker: node-modules\n",
	"apps/admin/yarn.lock":   "# This file is generated by running \"yarn install\"\n",

	// Bun, with a week counted the way pnpm counts. Bun reads seconds, so this is
	// 168 minutes and nobody is told.
	"apps/native/package.json": `{
  "name": "native",
  "packageManager": "bun@1.4.2"
}
`,
	"apps/native/bunfig.toml": `[install]
# A week.
minimumReleaseAge = 10080
`,
	"apps/native/bun.lock": `{"lockfileVersion":0,"workspaces":{}}` + "\n",

	// Deno, whose key is absent and whose lockfile is not frozen.
	"services/edge/deno.json": `{
  "name": "@acme/edge",
  "tasks": {
    "dev": "deno run -A main.ts"
  }
}
`,
	"services/edge/deno.lock": `{"version":"5","specifiers":{}}` + "\n",

	// uv, which writes the wait in words and has none.
	"services/api/pyproject.toml": `[project]
name = "api"
version = "0.1.0"

[tool.uv]
package = false
`,
	"services/api/uv.lock": "version = 1\nrequires-python = \">=3.12\"\n",

	// pip, whose configuration file a repository can hold but pip only reads when
	// it is told to.
	"services/api/requirements.txt": "requests==2.32.3\n",
}

// writeDoctorFixture builds the acceptance repository under a temporary directory
// and makes it the working directory.
func writeDoctorFixture(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	for name, content := range doctorFixture {
		writeFile(t, dir, name, content)
	}
	chdir(t, dir)
	return dir
}

// The scorecard names every manager in the repository and judges each setting in
// that manager's own unit. This is the M3 acceptance case.
func TestDoctorReportsEveryManager(t *testing.T) {
	writeDoctorFixture(t)

	code, stdout, stderr := run(t, "doctor", "--offline")
	if code != ExitOK {
		t.Fatalf("exit = %d, want 0 (stderr %q)\n%s", code, stderr, stdout)
	}
	for _, want := range []string{"npm", "pnpm", "yarn", "bun", "deno", "uv", "pip"} {
		if !strings.Contains(stdout, want) {
			t.Errorf("the scorecard does not name %s:\n%s", want, stdout)
		}
	}
	// The wrong unit, named as what it really is. Nothing else in this tool can
	// tell somebody that their week is 168 minutes. The human output wraps, so the
	// whole sentence is asserted on the json document instead and only its start
	// here.
	if !strings.Contains(stdout, "168 minutes") {
		t.Errorf("the bunfig.toml line does not say what 10080 seconds is:\n%s", stdout)
	}
	// The pnpm value is present and too short, which is a different sentence from
	// a missing one.
	if !strings.Contains(stdout, "60 is 1 hour") {
		t.Errorf("the pnpm line does not say what 60 means:\n%s", stdout)
	}
}

// --ci is what a job runs: it exits 1 on the settings that are missing or wrong at
// or above the policy's level, and the scorecard still says which they are.
func TestDoctorCIFailsOnProblems(t *testing.T) {
	writeDoctorFixture(t)

	code, stdout, stderr := run(t, "doctor", "--ci", "--offline")
	if code != ExitFindings {
		t.Fatalf("exit = %d, want 1 (stderr %q)\n%s", code, stderr, stdout)
	}
	if !strings.Contains(stdout, "wrong") || !strings.Contains(stdout, "missing") {
		t.Errorf("the scorecard does not say what failed:\n%s", stdout)
	}
}

// --fix writes each manager's own unit into each manager's own file, leaves the
// rest of every file alone, and has nothing to do the second time.
func TestDoctorFixWritesEachManagersUnit(t *testing.T) {
	dir := writeDoctorFixture(t)

	code, stdout, stderr := run(t, "doctor", "--fix", "--offline")
	if code != ExitOK {
		t.Fatalf("exit = %d, want 0 (stderr %q)\n%s", code, stderr, stdout)
	}

	// Three days, in the spelling each manager counts in, written into the files
	// that did not state the setting at all. Two of the fixture's files already
	// hold a wait of their own, and those two are reported and left alone: --fix
	// fills in what is absent and never argues with a line somebody wrote.
	wants := map[string]string{
		".npmrc":                      "min-release-age=3",
		"apps/admin/.yarnrc.yml":      "npmMinimalAgeGate: 4320",
		"services/edge/deno.json":     `"minimumDependencyAge": "P3D"`,
		"services/api/pyproject.toml": `exclude-newer = "3 days"`,
	}
	for name, want := range wants {
		if got := readFileAt(t, dir, name); !strings.Contains(got, want) {
			t.Errorf("%s does not hold %q:\n%s", name, want, got)
		}
	}

	// What was already in the files is still in them, comments included.
	keeps := map[string]string{
		".npmrc":                       "registry=https://registry.npmjs.org/",
		"apps/web/pnpm-workspace.yaml": "# Hold new releases back for a while.",
		"apps/admin/.yarnrc.yml":       "nodeLinker: node-modules",
		"apps/native/bunfig.toml":      "# A week.",
		"services/edge/deno.json":      `"dev": "deno run -A main.ts"`,
		"services/api/pyproject.toml":  `name = "api"`,
	}
	for name, keep := range keeps {
		if got := readFileAt(t, dir, name); !strings.Contains(got, keep) {
			t.Errorf("the edit to %s lost %q:\n%s", name, keep, got)
		}
	}

	// Three npm rules write into one .npmrc, and every one of them has to land. The
	// first version of this took a backup per rule, the names collided inside one
	// second, and two of the three settings were quietly not written.
	npmrc := readFileAt(t, dir, ".npmrc")
	for _, key := range []string{"min-release-age", "strict-allow-scripts", "strict-npmrc"} {
		if !strings.Contains(npmrc, key) {
			t.Errorf(".npmrc does not hold %s:\n%s", key, npmrc)
		}
	}
	// npm 12 already refuses a git or a URL dependency, so those two rules report
	// set and write nothing. A fixer that adds a line changing nothing is one
	// people stop trusting.
	for _, key := range []string{"allow-git", "allow-remote"} {
		if strings.Contains(npmrc, key) {
			t.Errorf(".npmrc was given %s, which npm 12 already does:\n%s", key, npmrc)
		}
	}
	// And one copy of the file as the person left it, not one per setting.
	if backups := backupsOf(t, dir, ".npmrc"); len(backups) != 1 {
		t.Errorf("%d backups of .npmrc, want 1: %v", len(backups), backups)
	}

	// A second run writes nothing at all, which is what makes this safe to put in
	// a script somebody runs on every checkout.
	before := readFileAt(t, dir, "apps/web/pnpm-workspace.yaml")
	code, second, stderr := run(t, "doctor", "--fix", "--offline")
	if code != ExitOK {
		t.Fatalf("the second run exited %d (stderr %q)\n%s", code, stderr, second)
	}
	if after := readFileAt(t, dir, "apps/web/pnpm-workspace.yaml"); after != before {
		t.Errorf("the second run changed the file:\n%s", after)
	}
	if strings.Contains(second, "fixed") {
		t.Errorf("the second run reports a change:\n%s", second)
	}
}

// The two flags contradict each other, and saying so is better than choosing one.
func TestDoctorRefusesFixWithCI(t *testing.T) {
	writeDoctorFixture(t)
	code, stdout, stderr := run(t, "doctor", "--fix", "--ci", "--offline")
	if code != ExitUsage || !strings.Contains(stderr, "cannot be combined") {
		t.Fatalf("exit = %d, stderr = %q\n%s", code, stderr, stdout)
	}
}

// The json document is what a script reads, so it has to carry the whole answer.
func TestDoctorJSONDocument(t *testing.T) {
	writeDoctorFixture(t)

	code, stdout, stderr := run(t, "--format", "json", "doctor", "--offline")
	if code != ExitOK {
		t.Fatalf("exit = %d, want 0 (stderr %q)", code, stderr)
	}
	var doc struct {
		Schema   string `json:"schema"`
		Root     string `json:"root"`
		Managers []struct {
			ID   string `json:"id"`
			Root string `json:"root"`
		} `json:"managers"`
		Results []struct {
			Rule    string `json:"rule"`
			Name    string `json:"name"`
			Status  string `json:"status"`
			File    string `json:"file"`
			Detail  string `json:"detail"`
			Manager string `json:"manager"`
		} `json:"results"`
		Summary struct {
			Managers    int            `json:"managers"`
			Results     int            `json:"results"`
			Statuses    map[string]int `json:"statuses"`
			ExitCode    int            `json:"exit_code"`
			ExitMeaning string         `json:"exit_meaning"`
		} `json:"summary"`
	}
	if err := json.Unmarshal([]byte(stdout), &doc); err != nil {
		t.Fatalf("the document is not json: %v\n%s", err, stdout)
	}
	if doc.Schema != "trustdiff.doctor/1" {
		t.Errorf("schema = %q", doc.Schema)
	}
	if doc.Summary.Managers != len(doc.Managers) || doc.Summary.Results != len(doc.Results) {
		t.Errorf("the summary does not agree with the document: %+v", doc.Summary)
	}
	// Both of the fixture's stated waits are values their manager accepts and
	// neither is the three days the policy asks for, which is what weak is for.
	if doc.Summary.Statuses["weak"] == 0 {
		t.Errorf("no result is weak, although two settings hold less than the policy asks:\n%s", stdout)
	}
	if doc.Summary.ExitCode != 0 || doc.Summary.ExitMeaning == "" {
		t.Errorf("summary exit = %d %q", doc.Summary.ExitCode, doc.Summary.ExitMeaning)
	}

	// The sentence that makes the scorecard worth reading, whole and unwrapped.
	var bun string
	for _, res := range doc.Results {
		if res.Rule == "DR030" {
			bun = res.Detail
		}
	}
	for _, want := range []string{"168 minutes", "1 week in minutes", "pnpm and Yarn count"} {
		if !strings.Contains(bun, want) {
			t.Errorf("the bun result does not say %q:\n%s", want, bun)
		}
	}
}

// The document says what actually gated the run. --fail-on gates findings about
// packages and has nothing to do with a scorecard, and a script that read it would
// believe the run was gated by something it was not.
func TestDoctorDocumentNamesTheGate(t *testing.T) {
	writeDoctorFixture(t)

	gate := func(t *testing.T, args ...string) string {
		t.Helper()
		_, stdout, _ := run(t, args...)
		var doc struct {
			Policy struct {
				FailOn string `json:"fail_on"`
			} `json:"policy"`
		}
		if err := json.Unmarshal([]byte(stdout), &doc); err != nil {
			t.Fatalf("decode: %v\n%s", err, stdout)
		}
		return doc.Policy.FailOn
	}
	if got := gate(t, "--format", "json", "doctor", "--offline"); got != "never" {
		t.Errorf("without --ci the document says the gate is %q, and nothing fails", got)
	}
	if got := gate(t, "--format", "json", "doctor", "--ci", "--offline"); got != "warn" {
		t.Errorf("with --ci the document says the gate is %q, want the policy's warn", got)
	}
	// --fail-on is about findings, so it must not change the answer.
	if got := gate(t, "--format", "json", "--fail-on", "never", "doctor", "--ci", "--offline"); got != "warn" {
		t.Errorf("--fail-on changed the doctor gate to %q", got)
	}
}

// A directory with nothing in it is not an error: the scorecard says it found no
// package manager, and a script that runs doctor over every repository it has does
// not have to special-case the empty one.
func TestDoctorOnARepositoryWithNoManager(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)
	code, stdout, stderr := run(t, "doctor", "--offline")
	if code != ExitOK {
		t.Fatalf("exit = %d, want 0 (stderr %q)\n%s", code, stderr, stdout)
	}
	if !strings.Contains(stdout, "no package manager found") {
		t.Errorf("the scorecard does not say the directory holds nothing to audit:\n%s", stdout)
	}
}

// readFileAt reads a file of the fixture, named the way the fixture names it.
func readFileAt(t *testing.T, dir, rel string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(rel)))
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

// backupsOf lists the backup copies written beside a file.
func backupsOf(t *testing.T, dir, rel string) []string {
	t.Helper()
	matches, err := filepath.Glob(filepath.Join(dir, filepath.FromSlash(rel)) + ".trustdiff-backup-*")
	if err != nil {
		t.Fatal(err)
	}
	return matches
}
